### ISSUE TITLE
Replace owning_ref

### ISSUE THREAD

**Issue by DieracDelta** [prometheus/client_rust#77]
Owning ref is (1) seemingly unmaintained since last commit was 2 years ago and (2) [unsound](https://github.com/noamtashma/owning-ref-unsoundness). Something else should probably be used.

**Comment by AbhijithGanesh** [comment]
True, this issue has popped up here in [LibP2P](https://github.com/libp2p/rust-libp2p/issues/2794) and other crates which uses this prometheus client

**Comment by AbhijithGanesh** [comment]
Can I work on patching the issue ? @mxinden

**Comment by AbhijithGanesh** [comment]
The `Owning_Ref` library is used at the following files:
 - [exemplar.rs](https://github.com/prometheus/client_rust/blob/master/src/metrics/exemplar.rs)
 - [family.rs](https://github.com/prometheus/client_rust/blob/master/src/metrics/family.rs)
 - [histogram.rs](https://github.com/prometheus/client_rust/blob/master/src/metrics/histogram.rs)

Histogram relevant files use this module, they cannot be used due to Security reasons! This needs to be patched where the usage of Owning_Ref is dropped!

**Comment by DieracDelta** [comment]
In other issues I see [this](https://docs.rs/reffers/latest/reffers/) being recommended. Haven't had a chance to look too deeply, but perhaps that is a suitable replacement?

**Comment by mxinden** [comment]
> Can I work on patching the issue ? @mxinden

Yes, for sure. Help is very much appreciated.

> In other issues I see [this](https://docs.rs/reffers/latest/reffers/) being recommended. Haven't had a chance to look too deeply, but perhaps that is a suitable replacement?

Can you tell whether it suffers the same unsoundness issues that `owning_ref` does?

---

We need `owning_ref` in _wrapper style_ metrics (e.g. `Family`), which internally use a `Mutex` though want to give users access to a reference of the underlying _wrapped_ metric (e.g. `Counter`). Given that this reference depends on the `MutexGuard`, we need to ensure that the `MutexGuard` lives long enough, i.e. throughout the lifetime of the reference of the _wrapped_ metric. Without keeping the `MutexGuard` alive, we invalidate the properties of the `Mutex` itself, namely mutual exclusive access to the _wrapped_ metric.

Thus far `owning_ref` offered a way to ship both the `MutexGuard` and the reference to the user, thus enforcing the lifetime bound.

Alternative approaches I can see:

- Use `parking_lot` and its [`RwLockGuard::map`](https://docs.rs/lock_api/latest/lock_api/struct.RwLockReadGuard.html#method.map) method.
- Take a `FnOnce` to access the _wrapped_ metric, instead of returning a reference to the _wrapped_ metric.
- Clone the _wrapped_ metric on each  access.

**Comment by AbhijithGanesh** [comment]
> > Can I work on patching the issue ? @mxinden
> 
> Yes, for sure. Help is very much appreciated.
> 
> > In other issues I see [this](https://docs.rs/reffers/latest/reffers/) being recommended. Haven't had a chance to look too deeply, but perhaps that is a suitable replacement?
> 
> Can you tell whether it suffers the same unsoundness issues that `owning_ref` does?
> 
> We need `owning_ref` in _wrapper style_ metrics (e.g. `Family`), which internally use a `Mutex` though want to give users access to a reference of the underlying _wrapped_ metric (e.g. `Counter`). Given that this reference depends on the `MutexGuard`, we need to ensure that the `MutexGuard` lives long enough, i.e. throughout the lifetime of the reference of the _wrapped_ metric. Without keeping the `MutexGuard` alive, we invalidate the properties of the `Mutex` itself, namely mutual exclusive access to the _wrapped_ metric.
> 
> Thus far `owning_ref` offered a way to ship both the `MutexGuard` and the reference to the user, thus enforcing the lifetime bound.
> 
> Alternative approaches I can see:
> 
>     * Use `parking_lot` and its [`RwLockGuard::map`](https://docs.rs/lock_api/latest/lock_api/struct.RwLockReadGuard.html#method.map) method.
> 
>     * Take a `FnOnce` to access the _wrapped_ metric, instead of returning a reference to the _wrapped_ metric.
> 
>     * Clone the _wrapped_ metric on each  access.

`Mutex` and `MutexGuard`are now being shipped by the standard crate in Rust, `std/sync` offers this as a solution. I would like to know if [std/sync](https://doc.rust-lang.org/std/sync/struct.MutexGuard.html) would be a good crate to replace!

**Comment by AbhijithGanesh** [comment]
@mxinden I went through the solution parking_lot offers. I am unable to figure out how to deal with the `MutexGuardedBuckets` and that is preventing me from fixing the solution. What should I do next/

**Comment by mxinden** [comment]
For the record, fix is released with `v0.18.0`.

https://github.com/prometheus/client_rust/pull/80
